### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BillAlex-BASoftware** [BillAlex-BASoftware/vue-jw-literature-service#1]
- [x] Personen (Familien) anlegen
- [ ] (Person als PD-Aufseher kennzeichnen)
- [ ] (Personen PD-Gruppe zuweisen)

- [x] Sprachen verwalten

- [x] Periodika-Typen verwalten
- [x] Bestellung pro Person verwalten
- [ ] Ausgabe Periodika
- [ ] Anzahl benötigt/bestellt & differenz

- [ ] Publikationen verwalten
- [ ] Eingang und Inventur pro Monat aufnehmen
- [ ] Eingang und Inventur Übersicht
- [ ] Archiv verwalten
- [ ] Bestellmengen festlegen
- [ ] Benötigte Bestellmengen ausgeben -> Hinweis auf Archiv

- [ ] Individuelle Bestellungen
- [ ] Versammlungsbestellungen
    - [ ] (Pro PD-Gruppe)
    
- [ ] Termine verwalten
